/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.Exposicion_registro.cerrarBD;
import static Interfaces.Usuario_registro.direccionBD;
import clases.Articulo;
import clases.Usuario;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;

/**
 *
 * @author EDU
 */
public class Articulo_registro extends javax.swing.JFrame {

    /**
     * Creates new form Articulo_registro
     */
    public Articulo_registro() {
        initComponents();
    }

    String cod_articulo = "";
    String nombre = "";
    String descripcion = "";
    int existencia = 0;
    int exis_max = 0;
    int exis_min = 0;
    double precio = 0;

    public static String direccionBD = ("C:\\Users\\usuario\\OneDrive\\Documentos\\GitHub\\ProyectoMuseo\\ProyectoMuseo\\guia.yapi");

    public void cargarDatos(ObjectContainer BaseD) {

        Articulo Exbuscar = new Articulo(null, null, null, 0, 0, 0, 0);
        ObjectSet result = BaseD.get(Exbuscar);
        mostrarDatos(result);
    }

    public void mostrarDatos(ObjectSet result) {
        String matrizArticulo[][] = new String[result.size()][7];
        if (result.size() == 0) {
            JOptionPane.showMessageDialog(null, "El articulo no existe");
        }

        for (int i = 0; i < result.size(); i++) {
            Articulo miArticulo = new Articulo();
            miArticulo = (Articulo) result.get(i);
            matrizArticulo[i][0] = miArticulo.getCod_articulo();
            matrizArticulo[i][1] = miArticulo.getNombre();
            matrizArticulo[i][2] = miArticulo.getDescripcion();
            matrizArticulo[i][3] = String.valueOf(miArticulo.getExistencia());
            matrizArticulo[i][4] = String.valueOf(miArticulo.getExis_max());
            matrizArticulo[i][5] = String.valueOf(miArticulo.getExis_min());
            matrizArticulo[i][6] = String.valueOf(miArticulo.getPrecio());

            tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(matrizArticulo, new String[]{"CODIGO", "NOMBRE", "DESCRIPCION", "EXITENCIA", "EXISTENCIA MAXIMA", "EXITENCIA MINIMA", "PRECIO"}));

        }

    }

    public void asignarVariables(ObjectContainer BaseD) {
        cod_articulo = txtCodigo.getText();
        nombre = txtNombre.getText();
        descripcion = txtDescripcion.getText();
        existencia = Integer.parseInt(txtExitencia.getText());
        exis_max = Integer.parseInt(txtExis_Max.getText());
        exis_min = Integer.parseInt(txtExi_min.getText());
        precio = Double.parseDouble(txtPr3ecio.getText());

    }

    public void limpiarDatos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtExitencia.setText("");
        txtExis_Max.setText("");
        txtExi_min.setText("");
        txtPr3ecio.setText("");
    }

    public static int comprobarArticulo(ObjectContainer BaseD, String cod_articulo) {
        Articulo Exbuscar = new Articulo(cod_articulo, null, null, 0, 0, 0, 0);
        ObjectSet result = BaseD.get(Exbuscar);
        return result.size();

    }

    public void crearArticulo(ObjectContainer BaseD) {
        asignarVariables(BaseD);
        if (comprobarArticulo(BaseD, cod_articulo) == 0) {
            Articulo Exnuevo = new Articulo(cod_articulo, nombre, descripcion, existencia, exis_max, exis_min, precio);
            BaseD.set(Exnuevo);
            JOptionPane.showMessageDialog(null, "Registrado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Artticulo ya registrado");

        }
    }

    public static void Cerrar_BD(ObjectContainer BaseD) {

        BaseD.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExitencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtExis_Max = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtExi_min = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPr3ecio = new javax.swing.JTextField();
        botonGuar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRO ARTICULOS ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 65, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 62, 148, -1));

        jLabel3.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 113, -1, -1));

        txtNombre.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 110, 142, -1));

        jLabel4.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel4.setText("Descripcion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 158, -1, -1));

        txtDescripcion.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 188, 214, 111));

        jLabel5.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel5.setText("Existencia:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 320, -1, -1));

        txtExitencia.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jPanel1.add(txtExitencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 317, 124, -1));

        jLabel6.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel6.setText("Existencia Maxima:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 365, -1, -1));

        txtExis_Max.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jPanel1.add(txtExis_Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 359, 58, -1));

        jLabel7.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel7.setText("Existencia Minima:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 403, -1, -1));

        txtExi_min.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jPanel1.add(txtExi_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 400, 62, -1));

        jLabel8.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jLabel8.setText("Precio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 451, -1, -1));

        txtPr3ecio.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        jPanel1.add(txtPr3ecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 448, 70, -1));

        botonGuar.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        botonGuar.setText("Guardar");
        botonGuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 496, -1, -1));

        botonMostrar.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        botonMostrar.setText("Cargar Datos");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 496, -1, -1));

        tablaArticulos.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaArticulos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 600, -1));

        botonRegresar.setFont(new java.awt.Font("Raanana", 0, 18)); // NOI18N
        botonRegresar.setText("Regresar");
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void botonGuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuarActionPerformed
        // TODO add your handling code here:
        ObjectContainer BaseD = Db4o.openFile(direccionBD);
        crearArticulo(BaseD);
        cerrarBD(BaseD);
    }//GEN-LAST:event_botonGuarActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
        ObjectContainer BaseD = Db4o.openFile(direccionBD);
        cargarDatos(BaseD);
        cerrarBD(BaseD);
    }//GEN-LAST:event_botonMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaArticulos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExi_min;
    private javax.swing.JTextField txtExis_Max;
    private javax.swing.JTextField txtExitencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPr3ecio;
    // End of variables declaration//GEN-END:variables
}
