/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.Exposicion_registro.cerrarBD;
import static Interfaces.Exposicion_registro.direccionBD;
import clases.Evento;
import clases.Exposicion;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author EDU
 */
public class Evento_modificar extends javax.swing.JFrame {

    /**
     * Creates new form Evento_modificar
     */
    public Evento_modificar() {
        initComponents();
    }
  String id_evento = "";
     String nombre_evento = "";
     String descripcion = "";
     Date fecha_inicio;
     Date fecha_final;
     String id_exposicion = "";

          public static String direccionBD = ("\\Users\\EDU\\Documents\\GitHub\\ProyectoMuseo\\ProyectoMuseo\\guia");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombretxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechai = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaf = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        codigotxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaevento = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        idextxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripciontxt = new javax.swing.JTextArea();
        btnguardar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        btncargar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 11, 13));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombretxt.setFont(new java.awt.Font("Raanana", 0, 14)); // NOI18N
        jPanel1.add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 166, -1));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo Evento:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 40));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del evento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(fechai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 224, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion del evento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha inicio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        jPanel1.add(fechaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 224, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha final:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        codigotxt.setFont(new java.awt.Font("Raanana", 0, 14)); // NOI18N
        jPanel1.add(codigotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 166, -1));

        tablaevento.setFont(new java.awt.Font("Raanana", 0, 14)); // NOI18N
        tablaevento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaevento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id exposicion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        idextxt.setFont(new java.awt.Font("Raanana", 0, 14)); // NOI18N
        jPanel1.add(idextxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 224, -1));

        descripciontxt.setColumns(20);
        descripciontxt.setFont(new java.awt.Font("Raanana", 0, 14)); // NOI18N
        descripciontxt.setRows(5);
        jScrollPane2.setViewportView(descripciontxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        btnguardar.setBackground(new java.awt.Color(0, 11, 13));
        btnguardar.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/actualizado.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.setBorder(null);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btnmostrar.setBackground(new java.awt.Color(0, 11, 13));
        btnmostrar.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        btnmostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/actualizar-pagina.png"))); // NOI18N
        btnmostrar.setText("MOSTRAR DATOS");
        btnmostrar.setBorder(null);
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, -1, -1));

        btncargar.setBackground(new java.awt.Color(0, 11, 13));
        btncargar.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        btncargar.setForeground(new java.awt.Color(255, 255, 255));
        btncargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/lupa.png"))); // NOI18N
        btncargar.setText("CARGAR DATOS");
        btncargar.setBorder(null);
        jPanel1.add(btncargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, 30));

        jPanel2.setBackground(new java.awt.Color(134, 153, 167));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 11, 13));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Minilogo.png"))); // NOI18N
        jLabel7.setText(" MODIFICAR EVENTOS ");

        botonRegresar.setBackground(new java.awt.Color(0, 11, 13));
        botonRegresar.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/deshacer_1.png"))); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(null);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 653, Short.MAX_VALUE)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1280, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 50, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1281, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
     
        
        ObjectContainer BaseD = Db4o.openFile(direccionBD);  
modificarEvento(BaseD);
cerrarBD(BaseD);
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
 ObjectContainer BaseD = Db4o.openFile(direccionBD);  
cargarTabla(BaseD);
cerrarBD(BaseD);
    }//GEN-LAST:event_btnmostrarActionPerformed

    
    //PARA CARGAR LOS DATOS DE LA BASE DE DATOS, ESTO TIENE QUE IR EN EL BOTON DE BUSCAR EXPOSICION.
    public void cargarDatos(ObjectContainer BaseD) {
        btnguardar.setEnabled(false);
        String CodigoEv;
        CodigoEv = codigotxt.getText();
        if (codigotxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un codigo");
        } else {
            if (comprobarEvento(BaseD, CodigoEv) == 0) {
                JOptionPane.showMessageDialog(null, "El evento no existe en la base de datos");

            } else {
                Evento Evbuscar = new Evento(CodigoEv, null, null , null, null, null);
                ObjectSet result = BaseD.get(Evbuscar);
                for (int i = 0; i < result.size(); i++) {
                    Evento Mievento = new Evento();
                    Mievento = (Evento) result.get(i);

                    nombretxt.setText(Mievento.getNombre_evento());
                    descripciontxt.setText(Mievento.getDescripcion());
                    idextxt.setText(Mievento.getId_exposicion());
                    fechai.setDate(Mievento.getFecha_inicio());
                    fechaf.setDate(Mievento.getFecha_final());

//                    if(ValidarCampos(Base D)){
                 btnguardar.setEnabled(true);
//                    
//                }
                    codigotxt.setEnabled(false);

                }
            }
        }

    }

    public void modificarEvento(ObjectContainer BaseD) {
        asignarVariables(BaseD);
        Evento Evmodi = new Evento(id_evento, null, null , null, null, null);
        ObjectSet result = BaseD.get(Evmodi);
        Evento Evmodificar = (Evento) result.next();

        Evmodificar.setNombre_evento(nombre_evento);
        Evmodificar.setDescripcion(descripcion);
        Evmodificar.setId_exposicion(id_exposicion);
        Evmodificar.setFecha_inicio(fecha_inicio);
        Evmodificar.setFecha_final(fecha_final);

        BaseD.set(Evmodificar);
        JOptionPane.showMessageDialog(null, "El evento fue modificado exitosamente");
        limpiarDatos();
    }

   public static int comprobarEvento(ObjectContainer BaseD, String codigo) {
        Evento Evbuscar = new Evento(codigo, null, null, null, null, null);
        ObjectSet result = BaseD.get(Evbuscar);
        return result.size();

    }

    public static void cerrarBD(ObjectContainer BaseD) {
        BaseD.close();
    }

     public void asignarVariables(ObjectContainer BaseD) {
          id_evento = codigotxt.getText();
      nombre_evento = nombretxt.getText();
      
      descripcion = descripciontxt.getText();
      
      fecha_inicio = fechai.getDate();
      
      fecha_final = fechaf.getDate();
      
      id_exposicion = idextxt.getText();
    }

    public void limpiarDatos() {
        codigotxt.setText("");
        nombretxt.setText("");
        descripciontxt.setText("");
idextxt.setText("");
    }
    
    //LO SIGUIENTE PARA CARGAR LOS DATOS REGISTRADOS EN LA TABLA
    
     public void cargarTabla(ObjectContainer BaseD){
        
        Evento Evbuscar = new Evento(null, null, null, null, null, null);
        ObjectSet result = BaseD.get(Evbuscar);
        mostrarDatos(result);
    }
    public void mostrarDatos(ObjectSet result) {
        String matrizEvento[][] = new String[result.size()][6];
        if(result.size() == 0){
            JOptionPane.showMessageDialog(null, "La exposicion no existe");
        }
        
        for (int i = 0; i < result.size(); i++) {
            Evento miEvento = new Evento();
            miEvento = (Evento) result.get(i);
            matrizEvento[i][0] = miEvento.getId_evento();
            matrizEvento[i][1] = miEvento.getId_evento();
            matrizEvento[i][2] = miEvento.getNombre_evento();
            matrizEvento[i][3] = miEvento.getDescripcion();
            matrizEvento[i][4] = String.valueOf(miEvento.getFecha_inicio());
            matrizEvento[i][5] = String.valueOf(miEvento.getFecha_final());

            tablaevento.setModel(new javax.swing.table.DefaultTableModel(matrizEvento, new String[]{"Codigo","Id Exposicion", "Nombre", "Descripcion","Fehca inicio", "Fecha Final"}));

        }

    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JTextField codigotxt;
    private javax.swing.JTextArea descripciontxt;
    private com.toedter.calendar.JDateChooser fechaf;
    private com.toedter.calendar.JDateChooser fechai;
    private javax.swing.JTextField idextxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTable tablaevento;
    // End of variables declaration//GEN-END:variables
}
